apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.containers.image }}  
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: BOT_TOKEN
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: API_TOKEN
        - name: JENKINS_URL
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: JENKINS_URL
        - name: JENKINS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: JENKINS_PASSWORD
        - name: JENKINS_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: JENKINS_USERNAME