apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telegrambot
  template:
    metadata:
      labels:
        app: telegrambot
    spec:
      containers:
      - name: telegrambot
        image: rolandgryddynamics/jenkins:12
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: BOT_TOKEN
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: API_TOKEN
        - name: JENKINS_URL
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: JENKINS_URL
        - name: JENKINS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: JENKINS_PASSWORD
        - name: JENKINS_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: JENKINS_USERNAME