# this playbook should work only one time or if you updated secret.yml/deployment.yml
---
 - hosts: worker
   vars:
    source_secret_file: "../kubernetes/secrets.yaml"
    source_deploy_file: "../kubernetes/deployment.yaml"
    destin_file: "/home/ubuntu/"
   tasks:
    - name: copy secret file
      copy: src={{ source_secret_file }} dest={{ destin_file }} mode=0555

    - name: create secret file
      shell: kubectl apply -f secrets.yaml

    - name: copy deployment file
      copy: src={{ source_deploy_file }} dest={{ destin_file }} mode=0555

    - name: create deployment file
      shell: kubectl apply -f deployment.yaml