--- 
- hosts: prod
  become: true
  vars:
    docker_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    docker_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
  tasks:
    - name: Add Docker APT key
      apt_key:
        url: "{{ docker_gpg_key_url }}"
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"
        state: present

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present



