---
- name: Install Helm on Ubuntu
  hosts: worker
  become: true

  tasks:
    - name: Add Helm GPG key
      shell: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null

    - name: Install apt-transport-https package
      apt:
        name: apt-transport-https
        state: present

    - name: Add Helm repository
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

    - name: Add Helm repository
      shell: sudo apt-get install helm