---
 - hosts: worker
   vars:
    source_deploy_file: "../kubernetes/deployment.yaml"
    destin_file: "/home/ubuntu/"
   tasks:
    - name: copy deployment file
      copy: src={{ source_deploy_file }} dest={{ destin_file }} mode=0555

    - name: create deployment file
      shell: kubectl apply -f deployment.yaml